name: Bug Report
description: Report a bug encountered while operating the application
labels: [bug, untriaged]
body:
  - type: markdown
    attributes:
      value: |
        If you encounter this problem too, leave a thumbs up 👍

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it (as minimally and precisely as possible)
      description: Steps to reproduce the behavior.
      placeholder: |
        Please provide a **MINIMAL REPRO PROJECT** and the **STEPS TO REPRODUCE**
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Please provide steps to workaround this problem if possible

  - type: dropdown
    id: platforms
    attributes:
      label: Affected platforms
      multiple: true
      description: Select all the platforms on which you encountered this issue. It's OK if you couldn't try every platform yourself.
      options:
        - Linux
        - macOS
        - Windows

  - type: dropdown
    id: app-kind
    attributes:
      label: Affected software kind
      multiple: true
      description: Select all the platforms on which you encountered this issue.
      options:
        - GUI app
        - CLI app
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: Which version are you using? The version number can be found by going to Settings > About
      placeholder: "e.g. Version: 1.0.0.0 | X64; OS Version: 10.0.22000.282"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant Assets/Logs
      description: |
        A list of assets (logs, screenshots, etc) relevant to this bug.

        Tip: You can attach image(s) or log file(s) by clicking this area to highlight it and then dragging files in.
      placeholder: |
        To upload the log, access it from Settings -> About -> Open log location; Or
        - Copy the `logs.txt` file from `%cache-file%`
        - Drag and drop them into this text area.
